version: '3.8'

services:
  box0:
    container_name: box0
    restart: always
    depends_on:
      - ipfs0
      - cluster0
    build:
      context: ../../
      dockerfile: ./apps/box/Dockerfile
    volumes:
      - ./data/box0/data:/opt/apps/box/data
    environment:
      NODE_ENV: "production"
      FULA_IPFS_HTTP: "http://cluster0:9095"
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001"

  ipfs0:
    container_name: ipfs0
    build:
      context: .
      dockerfile: ./ipfs/Dockerfile
    ports:
      - "4002:4001" # ipfs swarm - expose if needed/wanted
      - "5002:5001" # ipfs api - expose if needed/wanted
      - "8082:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./data/ipfs0:/data/ipfs
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment", "--enable-namesys-pubsub"]


  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      # Open API port (allows ipfs-cluster-ctl usage on host)
      - "127.0.0.1:9094:9094"
      - "9095:9095"
      # The cluster swarm port would need  to be exposed if this container
      # was to connect to cluster peers on other hosts.
      # But this is just a testing cluster.
      # - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./data/cluster0:/data/ipfs-cluster

  box1:
    container_name: box1
    restart: always
    depends_on:
      - ipfs1
      - cluster1
    build:
      context: ../../
      dockerfile: ./apps/box/Dockerfile
    volumes:
      - ./data/box1/data:/opt/apps/box/data
    environment:
      NODE_ENV: "production"
      FULA_IPFS_HTTP: "http://cluster1:9095"
    ports:
      - "4004:4001" # ipfs swarm - expose if needed/wanted
      - "5004:5001"

  ipfs1:
    container_name: ipfs1
    build:
      context: .
      dockerfile: ./ipfs/Dockerfile
    volumes:
      - ./data/ipfs1:/data/ipfs
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment", "--enable-namesys-pubsub"]

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
    volumes:
      - ./data/cluster1:/data/ipfs-cluster


